config/routes.rb
Rails.application.routes.draw do
  resources :student_infos
  get 'welcome/index'
  get '/index' => 'welcome#index'
  get '/about' => 'welcome#about'
  get '/studentInfo' => 'student_infos#index'

  
  root 'welcome#index'

end

app/models/student_info.rb
class StudentInfo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/student_infos_controller.rb
class StudentInfosController < ApplicationController
  before_action :set_student_info, only: [:show, :edit, :update, :destroy]

  # GET /student_infos
  # GET /student_infos.json
  def index
    @student_infos = StudentInfo.all
  end

  # GET /student_infos/1
  # GET /student_infos/1.json
  def show
  end

  # GET /student_infos/new
  def new
    @student_info = StudentInfo.new
  end

  # GET /student_infos/1/edit
  def edit
  end

  # POST /student_infos
  # POST /student_infos.json
  def create
    @student_info = StudentInfo.new(student_info_params)

    respond_to do |format|
      if @student_info.save
        format.html { redirect_to @student_info, notice: 'Student info was successfully created.' }
        format.json { render :show, status: :created, location: @student_info }
      else
        format.html { render :new }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_infos/1
  # PATCH/PUT /student_infos/1.json
  def update
    respond_to do |format|
      if @student_info.update(student_info_params)
        format.html { redirect_to @student_info, notice: 'Student info was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_info }
      else
        format.html { render :edit }
        format.json { render json: @student_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_infos/1
  # DELETE /student_infos/1.json
  def destroy
    @student_info.destroy
    respond_to do |format|
      format.html { redirect_to student_infos_url, notice: 'Student info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_info
      @student_info = StudentInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_info_params
      params.require(:student_info).permit(:name, :number, :major, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
  def data
  end
  def add
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_infos_helper.rb
module StudentInfosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jocelyn's page</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/student_infos/_form.html.erb
<%= form_for(@student_info) do |f| %>
  <% if @student_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_info.errors.count, "error") %> prohibited this student_info from being saved:</h2>

      <ul>
      <% @student_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "姓名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "学号" %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label "专业" %><br>
    <%= f.text_field :major %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "添加"%>
  </div>
<% end %>

app/views/student_infos/_partForm.html.erb
<%= form_for(@student_info) do |f| %>
  <% if @student_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_info.errors.count, "error") %> prohibited this student_info from being saved:</h2>

      <ul>
      <% @student_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "姓名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "学号" %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label "专业" %><br>
    <%= f.text_field :major %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
 
<% end %>

app/views/student_infos/edit.html.erb
<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="">高级软件工程</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/studentInfo">数据</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<!-- +++++ Welcome Section +++++ -->
<div id="ww">
  <div class="container">
    <div class="row">
      <h1>编辑学生信息</h1>

      <%= render 'partForm' %>
      
      <%= link_to '确定', @student_info %> |
      <%= link_to '返回', student_infos_path %>
    </div><!-- /row -->
  </div> <!-- /container -->
</div><!-- /ww -->


<!-- +++++ Footer Section +++++ -->
	
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<p>中国科学院大学，北京, 中国</p>
			</div>
			
		</div>
	
	</div>
</div>

app/views/student_infos/index.html.erb
<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="">高级软件工程</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/studentInfo">数据</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<!-- +++++ Welcome Section +++++ -->
<div id="ww">
  <div class="container">
      <div class="row">
        <p id="notice"><%= notice %></p>
        <table class="table table-striped">
          <caption><h2>当前学生列表</h2></caption>
          <thead>
              <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Major</th>
                <th>Email</th>
                <th colspan="3"></th>
              </tr>
          </thead>
          <tbody>
              <% @student_infos.each do |student_info| %>
              <tr>
                <td><%= student_info.name %></td>
                <td><%= student_info.number %></td>
                <td><%= student_info.major %></td>
                <td><%= student_info.email %></td>
                <td><%= link_to '编辑', edit_student_info_path(student_info) %></td>
                <td><%= link_to '删除', student_info, method: :delete, data: { confirm: '确定删除该学生信息?' } %></td>
              </tr>
              <% end %>
          </tbody>
      </table>
      <br>
      <button type="button" class="btn btn-default" onClick="newStudent()">添加学生</button>

    </div><!-- /row -->
  </div> <!-- /container -->
</div><!-- /ww -->


<!-- +++++ Footer Section +++++ -->
	
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<p>中国科学院大学，北京, 中国</p>
			</div>
			
		</div>
	
	</div>
</div>

app/views/student_infos/new.html.erb
<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="">高级软件工程</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/studentInfo">数据</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<!-- +++++ Welcome Section +++++ -->
<div id="ww">
  <div class="container">
    <div class="row">
      <h2>添加学生信息</h2>
      <%= render 'form' %>
      <%= link_to '返回', student_infos_path %>
    </div><!-- /row -->
  </div> <!-- /container -->
</div><!-- /ww -->


<!-- +++++ Footer Section +++++ -->
	
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<p>中国科学院大学，北京, 中国</p>
			</div>
		</div>
	</div>
</div>

app/views/student_infos/show.html.erb
<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="">高级软件工程</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/studentInfo">数据</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<!-- +++++ Welcome Section +++++ -->
<div id="ww">
    <div class="container">
        <div class="row">
            <p id="notice"><%= notice %></p>
            <p>
              <strong>姓名:</strong>
              <%= @student_info.name %>
            </p>
            
            <p>
              <strong>学号:</strong>
              <%= @student_info.number %>
            </p>
            
            <p>
              <strong>专业:</strong>
              <%= @student_info.major %>
            </p>
            
            <p>
              <strong>Email:</strong>
              <%= @student_info.email %>
            </p>
            
            <%= link_to '编辑', edit_student_info_path(@student_info) %> |
            <%= link_to '返回', student_infos_path %>

        </div><!-- /row -->
    </div> <!-- /container -->
</div><!-- /ww -->


<!-- +++++ Footer Section +++++ -->
	
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<p>中国科学院大学，北京, 中国</p>
			</div>
			
		</div>
	
	</div>
</div>

app/views/welcome/about.html.erb
<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">高级软件工程</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/studentInfo">数据</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<!-- +++++ Welcome Section +++++ -->
<div id="ww">
  <div class="container">
    <div class="row">
    	<div class="col-lg-8 col-lg-offset-2 centered">
        <%= image_tag "user.png" %>
    		<h1>关于Jocelyn</h1>
    		<p>Ruby On Rails 新手一枚</p>
    	</div><!-- /col-lg-8 -->
    </div><!-- /row -->
  </div> <!-- /container -->
</div><!-- /ww -->
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<p>中国科学院大学，北京, 中国</p>
			</div>
			
		</div>
	
	</div>
</div>

app/views/welcome/index.html.erb
<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="">高级软件工程</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/studentInfo">数据</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<!-- +++++ Welcome Section +++++ -->
<div id="ww">
  <div class="container">
    <div class="row">
    	<div class="col-lg-8 col-lg-offset-2 centered">
    		<h1>Hi, I am Jocelyn!</h1>
    		<p>下面的两个按钮是作业1的内容</p>
    		<button type="button" class="btn btn-default"><a href="http://onestop.ucas.edu.cn/" target="_blank">点击我进行超链接跳转</a></button>
    		<button type="button" class="btn btn-default" onclick="showTime()">点击我显示当前时间</button>
    		<p id="show"></p>
    		<p>上方的导航栏用以实现页面跳转</p>
    		<p>导航栏中“数据”页面是作业2的内容</p>
    		
    	
    	</div><!-- /col-lg-8 -->
    </div><!-- /row -->
  </div> <!-- /container -->
</div><!-- /ww -->
<!-- +++++ Footer Section +++++ -->
	
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<p>中国科学院大学，北京, 中国</p>
			</div>
			
		</div>
	
	</div>
</div>